services:
  redis:
    image: redis:alpine
    container_name: pol-redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pol-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - redis
    restart: always

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pol-celery
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - redis
      - backend
    restart: always

