# Generated by Django 5.2.11 on 2026-02-24 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('pol_type', models.CharField(choices=[('petroleum', 'Petroleum'), ('oil', 'Oil'), ('lubricant', 'Lubricant'), ('other', 'Other')], default='petroleum', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_unit', models.CharField(default='Liter', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('shelf_life', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_unit', models.CharField(default='Liter', max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('category', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='sell', max_length=10)),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('unlisted', 'Unlisted'), ('sold', 'Sold')], default='listed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pol_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='admin_dashboard.politem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
