# Generated by Django 5.2.12 on 2026-03-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_sds_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pol_type',
            field=models.CharField(choices=[('petroleum', 'Petroleum'), ('oil', 'Oil'), ('lubricant', 'Lubricant')], default='petroleum', max_length=20),
        ),
    ]
