# Generated by Django 5.2.11 on 2026-03-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_delete_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='politem',
            name='msds_file',
            field=models.FileField(blank=True, null=True, upload_to='msds/'),
        ),
    ]
