# Generated by Django 5.2.12 on 2026-03-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_politem_msds_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politem',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='politem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='politem',
            name='company',
        ),
        migrations.RemoveField(
            model_name='politem',
            name='usage_rate',
        ),
    ]
