# Generated by Django 5.2.12 on 2026-03-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_remove_politem_batch_number_remove_politem_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='politem',
            name='pol_type',
        ),
    ]
