# Generated by Django 5.2.12 on 2026-03-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_remove_politem_location_remove_politem_pol_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient_email',
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('alert', 'Alert'), ('pending', 'Pending')], default='alert', max_length=20),
        ),
    ]
