# Generated by Django 5.2.12 on 2026-03-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_remove_notification_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politem',
            name='alt_part_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='politem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='politem',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('expired', 'Expired')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='politem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='politem',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='politem',
            name='mil_spec',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='politem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='politem',
            name='pol_type',
            field=models.CharField(choices=[('petroleum', 'Petroleum'), ('oil', 'Oil'), ('lubricant', 'Lubricant'), ('grease', 'Grease'), ('coolant', 'Coolant'), ('hydraulic', 'Hydraulic'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='politem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='politem',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='politem',
            name='uom',
            field=models.CharField(default='Liter', help_text='Unit of Measurement', max_length=50),
        ),
        migrations.AddField(
            model_name='politem',
            name='usage_rate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='politem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='politem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stock/Availability', max_digits=10),
        ),
    ]
