# Generated by Django 5.2.12 on 2026-03-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_politem_alt_part_number_politem_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politem',
            name='condition',
            field=models.CharField(choices=[('new_pol', 'New POL'), ('leftover_pol', 'Leftover POL'), ('opened_pol', 'Opened POL')], default='new_pol', max_length=20),
        ),
        migrations.AlterField(
            model_name='politem',
            name='pol_type',
            field=models.CharField(choices=[('petroleum', 'Petroleum'), ('oil', 'Oil'), ('lubricant', 'Lubricant')], default='petroleum', max_length=20),
        ),
    ]
