# Generated by Django 5.2.12 on 2026-03-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_alter_politem_condition_alter_politem_pol_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politem',
            name='uom',
            field=models.CharField(choices=[('QT', 'Quart'), ('OZ', 'Ounce'), ('LB', 'Pound'), ('RL', 'Roll'), ('EA', 'Each'), ('GAL', 'Gallon'), ('ML', 'Millilitre'), ('PT', 'Pint'), ('KT', 'Kit'), ('GM', 'Gram'), ('FT', 'Feet'), ('SQ ST', 'Square Feet'), ('YD', 'Yard'), ('CC', 'Cubic Centimeter')], default='GAL', help_text='Unit of Measurement', max_length=50),
        ),
    ]
