# Generated by Django 5.2.12 on 2026-03-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_alter_politem_uom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politem',
            old_name='usage_rate',
            new_name='balance',
        ),
    ]
