# Generated by Django 5.2.12 on 2026-03-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_rename_usage_rate_to_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='politem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pol_images/'),
        ),
    ]
