# Generated by Django 5.2.12 on 2026-03-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_points',
            field=models.TextField(blank=True, help_text='Contact points / key contacts'),
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_conditions',
            field=models.TextField(blank=True, help_text='Terms & Conditions text'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_conditions_file',
            field=models.FileField(blank=True, null=True, upload_to='terms_conditions/'),
        ),
    ]
