# Generated by Django 5.2.11 on 2026-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_profile_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('business', 'Business'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
