# Generated by Django 5.2.12 on 2026-03-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text="User's Selling ID (Connect Account - acct_XXXX)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text="User's Buying ID (Customer ID - cus_XXXX)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False, help_text='True if Connect onboarding is finished'),
        ),
    ]
