# Generated by Django 5.2.12 on 2026-03-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_order_listing_order_platform_commission_order_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadminnotification',
            name='type',
            field=models.CharField(choices=[('new_order', 'New Order Placed'), ('new_user', 'New User Registered')], max_length=20),
        ),
    ]
